### PR TITLE
View bounds animation

### PR DESCRIPTION
**Pull request by nick-thompson**
Wrapping up what we started on #31, @JoshMarler mind taking a quick look?

### CODE REVIEW

**Comment by JoshMarler** [comment]
@nick-thompson, dope. One is very excited. Will look over now.

**Comment by JoshMarler** [comment]
@nick-thompson, Awesome, awesome, awesome. That is all. 

Ha no seriously looks great. I pulled it down and ran the example. I like the interface now. Very neat. I wonder if doing a similar thing for opacity handled in `View` would be worth while. 

i.e. 

`<View opacityAnimated />`

That would match the capabilities of `juce::ComponentAnimator`. It should be able to take the same set of properties as the `layoutAnimated` prop/object. 

Just food for thought, that could be argued as a task an `AnimatedValue` implementation but I feel like it could be a valuable half-way house? I'd be happy to implement and just follow the ground work you've already laid down ?

Things like the switch on `EasingType` for the `lerp` call could be pulled to some generic location to be shared by `BoundsAnimator` and `OpacityAnimator`. 

Looks great though. Looking forward to using this, I've a carousel like component to implement!

**Comment by nick-thompson** [comment]
Great, happy to hear that!

Yea I kind of just skipped right over opacity, maybe just due to personal bias (I'm realizing I don't often use opacity animation, I guess!). I'd be curious to hear the use cases you have in mind?

Also wondering if it'd make sense to just add opacity animation to the same prop?

```js
<View {...styles.container} />
```

**Comment by JoshMarler** [comment]
> Great, happy to hear that!
> 
> Yea I kind of just skipped right over opacity, maybe just due to personal bias (I'm realizing I don't often use opacity animation, I guess!). I'd be curious to hear the use cases you have in mind?
> 
> Also wondering if it'd make sense to just add opacity animation to the same prop?
> 
> ```js
> <View {...styles.container} />
> 
> const styles = {
>     container: {
>         layoutAnimated: {
>             duration: 200.0,
>             easing: View.EasingFunctions.quadraticInOut,
>             opacityStart: 0.1,
>             opacityEnd: 0.9
>         }
>     }
> };
> ```
> 
> I realize opacity isn't quite "layout," but in another sense it seems to make sense to group them.

Yeah interesting. I'm no sure whether they should be kept distinct or not at the moment. To be honest, I haven't required opacity animation just yet, I'll take a read through my current project's design specs again and see if I need it. 

I don't have strong feelings about opacity animation being a distinct property.... That might be one to muse over.

**Comment by nick-thompson** [comment]
:+1: sounds good, let me know! Maybe it's better to wait until we have a concrete case to help inform the API design. If you have a related feature in your current project, let's discuss here. Otherwise, I think we go ahead with layout animation for now and return to opacity when that first concrete case comes up.

**Comment by JoshMarler** [comment]
I will have an example for opacity transitions (So a clever UX man tells me) but for now I agree, just go with layout and we can deal with opacity later. Merge it, merge it, merge it! 

https://media.giphy.com/media/69iB0zVgoKkatcVDrA/giphy.gif

**Comment by nick-thompson** [comment]
Done! :D

**Pull request merged**
