### PR TITLE
Fix ReactApplicationRoot hiding View::addChild

### PR DESCRIPTION
**Pull request by JoshMarler**
@nick-thompson, mind giving this a quick once over and then I'll bump npm. Fixies shadowing issues on mac

### CODE REVIEW

**Comment by nick-thompson** [comment]
Yup! This is great. Would you mind bumping our CMakeLists while we're here to turn on higher warning levels in our CI build? Hoping to prevent another break like that :)

Ready to merge when you've got the npm bump

**Comment by JoshMarler** [comment]
@nick-thompson, mind if I play with warning settings in separate commit? I'm not totally sure what the correct warning flags to use along with the juce recommended helpers are. Yep cool will sort package bump.

**Comment by nick-thompson** [comment]
Yup, no problem

**Comment by JoshMarler** [comment]
@nick-thompson, Have bumped react-juce so good to merge.

**Pull request merged**
